version: "3.9"

services:
  server:
    build:
      context: ./backend/area-back
    ports:
      - "3000:3000"
    container_name: server_service

  client_web:
    build:
      context: ./frontend/area-front
    ports:
      - "8081:8081"
    container_name: client_web_service
    depends_on:
      - server

