name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Backend Dependencies
      run: cd backend/area-back && npm install

    - name: Install Frontend Dependencies
      run: cd frontend/area-front && npm install

    - name: Run Code Formatter
      run: |
        cd backend/area-back && npx prettier --write .
        cd ../../frontend/area-front && npx prettier --write .


    - name: Run Unit Tests
      run: |
        cd backend/area-back && npm test
        cd ../../frontend/area-front && npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: SSH and Pull Latest Changes
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/B-DEV-500-RUN-5-2-area-cedric.roulof
          docker-compose down --volumes --remove-orphans
          git pull origin main
          docker-compose up --build -d
